/**
 * This model represents categories.
 * Uses values generated by corresponding classes
 * 
 * @export
 * @emulator
 */
export enum Category{
    History,
    Favourite,
    Recommend,
    Current
}