"use strict";
/**
 * This model represents categories.
 * Uses values generated by corresponding classes
 *
 * @export
 * @emulator
 */
(function (Category) {
    Category[Category["History"] = 0] = "History";
    Category[Category["Favourite"] = 1] = "Favourite";
    Category[Category["Recommend"] = 2] = "Recommend";
    Category[Category["Current"] = 3] = "Current";
})(exports.Category || (exports.Category = {}));
var Category = exports.Category;
